# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-03 19:39:53
"""
import arcpy
from sys import argv

output_directory = r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4bOutput"
output_directory_raster = r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb"

Chosen_ElevStrmHlls=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model2Output\StrmHillElev"
SoilCarbonFinal_5_=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4bOutput\SoilCarbonFinal"
SoilCarbon=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\SoilCarbon"

def Model22(Chosen_ElevStrmHlls, SoilCarbonFinal_5_, SoilCarbon):  # 4b Pre-event Soil Carbon Calculation_rev

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(cellSize="MAXOF", extent="526570.079847613 1644641.67664025 661135.079847613 1714721.67664025", mask=r"C:\Users\taller\Desktop\ArianaRiosArcGIS\PythonModels\Modelo_Carbono_Diana_Data\Landslides_SLM_Red_2018_N\Insumos_Red_2018_N15m\dem15aff", 
                          snapRaster=r"C:\Users\taller\Desktop\ArianaRiosArcGIS\PythonModels\Modelo_Carbono_Diana_Data\Landslides_SLM_Red_2018_N\Insumos_Red_2018_N15m\dem15aff"):

        # Process: Add Field (2) (Add Field) (management)
        SoilCarbon_4_ = arcpy.management.AddField(in_table=SoilCarbon, field_name="SoilC_Mgh", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

        # Process: Calculate Field (2) (Calculate Field) (management)
        SoilCarbon_5_ = arcpy.management.CalculateField(in_table=SoilCarbon_4_, field="SoilC_Mgh", expression="!SoilCarbon_table_MEAN! /100", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Identity (Identity) (analysis)
        SoilCarbonPoly = output_directory + r"\SoilCarbonPoly"
        arcpy.analysis.Identity(in_features=Chosen_ElevStrmHlls, identity_features=SoilCarbon_5_, out_feature_class=SoilCarbonPoly, join_attributes="ALL", cluster_tolerance="", relationship="NO_RELATIONSHIPS")

        # Process: Add Field (3) (Add Field) (management)
        SoilCarbonPoly_2_ = arcpy.management.AddField(in_table=SoilCarbonPoly, field_name="SoilC_Mg", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]
        
        # Add a new field for area in VegElevHill_2_
        arcpy.management.AddField(SoilCarbonPoly_2_, "F_AREA", "DOUBLE")

        # Calculate the area for each feature in VegElevHill_2_
        arcpy.management.CalculateField(SoilCarbonPoly_2_, "F_AREA", "!SHAPE.area!", "PYTHON3")

        # Process: Calculate Areas (Calculate Areas) (stats)
        SoilCarbonPolyArea = output_directory + r"\SoilCarbonPolyArea"
        arcpy.management.CopyFeatures(SoilCarbonPoly_2_, SoilCarbonPolyArea)

        # Process: Calculate Field (3) (Calculate Field) (management)
        SoilCarbonPolyArea_2_ = arcpy.management.CalculateField(in_table=SoilCarbonPolyArea, field="SoilC_Mg", expression="!SoilC_Mgh! * !F_AREA! /10000", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Select (2) (Select) (analysis)
        SoilStreamCarbon = output_directory + r"\SoilStreamCarbon"
        arcpy.analysis.Select(in_features=SoilCarbonPolyArea_2_, out_feature_class=SoilStreamCarbon, where_clause="StrOrder > 0")

        # Process: Calculate Field (4) (Calculate Field) (management)
        SoilStreamCarbon_2_ = arcpy.management.CalculateField(in_table=SoilStreamCarbon, field="SoilC_Mg", expression="0", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Update (Update) (analysis)
        SoilCarbonFinal = output_directory + r"\SoilCarbonFinal"
        arcpy.analysis.Update(in_features=SoilCarbonPolyArea_2_, update_features=SoilStreamCarbon_2_, out_feature_class=SoilCarbonFinal, keep_borders="BORDERS", cluster_tolerance="")

        # Process: Add Field (4) (Add Field) (management)
        SoilCarbonFinal_2_ = arcpy.management.AddField(in_table=SoilCarbonFinal, field_name="Elev_m", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

        # Process: Calculate Field (5) (Calculate Field) (management)
        SoilCarbonFinal_3_ = arcpy.management.CalculateField(in_table=SoilCarbonFinal_2_, field="Elev_m", expression="!gridcode!", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Delete Field (Delete Field) (management)
        SoilCarbonFinal_5_ = arcpy.management.DeleteField(in_table=SoilCarbonFinal_3_, drop_field=["FID_StrmHillElev", "FID_Elevation_RioHondo75m", "Shape_Leng", "SoilCarbon_table_OBJECTID", "SoilCarbon_table_COUNT", "SoilCarbon_table_AREA", "StrmHillElev_STRM_ORD", "FID_streamhillslope", "GRID_CODE_1", "Soils_clip_AREA", "Soils_clip_PERIMETER", "Soils_clip_SSUELOS_", "Soils_clip_SSUELOS_ID", "Soils_clip_AERA__KM2_", "Soils_clip_ACRES", "Soils_clip_Shape_Leng", "Soils_clip_Shape_Le_1", "SoilCarbon_table_SIMBOLO"])[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb", workspace=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb"):
        Model22(*argv[1:])
