# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-03 19:50:24
"""
import arcpy
from sys import argv

def Model23(RootCarbonFinal_4_=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4bOutput\RootCarbonFinal", RootCarbon= r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model3cOutput\RootCarbon"):  # 4c Pre-event Root Carbon Calculation_rev

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(cellSize="MAXOF", extent="526570.079847613 1644641.67664025 661135.079847613 1714721.67664025", mask=r"C:\Users\taller\Desktop\ArianaRiosArcGIS\PythonModels\Modelo_Carbono_Diana_Data\Landslides_SLM_Red_2018_N\Insumos_Red_2018_N15m\dem15aff", 
                          snapRaster=r"C:\Users\taller\Desktop\ArianaRiosArcGIS\PythonModels\Modelo_Carbono_Diana_Data\Landslides_SLM_Red_2018_N\Insumos_Red_2018_N15m\dem15aff"):

        # Process: Add Field (2) (Add Field) (management)
        RootCarbon_2_ = arcpy.management.AddField(in_table=RootCarbon, field_name="RootC_Mgh", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

        # Process: Calculate Field (2) (Calculate Field) (management)
        RootCarbon_3_ = arcpy.management.CalculateField(in_table=RootCarbon_2_, field="RootC_Mgh", expression="!RootCarb_table_MEAN! /100", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Add Field (3) (Add Field) (management)
        RootCarbon_4_ = arcpy.management.AddField(in_table=RootCarbon_3_, field_name="RootC_Mg", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]
        
        # Add a new field for area in VegElevHill_2_
        arcpy.management.AddField(RootCarbon_4_, "F_AREA", "DOUBLE")

        # Calculate the area for each feature in VegElevHill_2_
        arcpy.management.CalculateField(RootCarbon_4_, "F_AREA", "!SHAPE.area!", "PYTHON3")

        # Process: Calculate Areas (Calculate Areas) (stats)
        RootCarbon_Area = r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4cOutput\RootCarbon_Area"
        arcpy.management.CopyFeatures(RootCarbon_4_, RootCarbon_Area)

        # Process: Calculate Field (3) (Calculate Field) (management)
        RootCarbon_Area_2_ = arcpy.management.CalculateField(in_table=RootCarbon_Area, field="RootC_Mg", expression="!RootC_Mgh! * !F_AREA! /10000", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Select (2) (Select) (analysis)
        RootStreamCarbon = r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4cOutput\RootStreamCarbon"
        arcpy.analysis.Select(in_features=RootCarbon_Area_2_, out_feature_class=RootStreamCarbon, where_clause="StrmHillElev_StrOrder > 0")

        # Process: Calculate Field (4) (Calculate Field) (management)
        RootStreamCarbon_2_ = arcpy.management.CalculateField(in_table=RootStreamCarbon, field="RootC_Mg", expression="0", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Update (Update) (analysis)
        RootCarbonFinal = r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb\Model4cOutput\RootCarbonFinal"
        arcpy.analysis.Update(in_features=RootCarbon_Area_2_, update_features=RootStreamCarbon_2_, out_feature_class=RootCarbonFinal, keep_borders="BORDERS", cluster_tolerance="")

        # Process: Add Field (4) (Add Field) (management)
        RootCarbonFinal_2_ = arcpy.management.AddField(in_table=RootCarbonFinal, field_name="Elev_m", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

        # Process: Calculate Field (5) (Calculate Field) (management)
        RootCarbonFinal_3_ = arcpy.management.CalculateField(in_table=RootCarbonFinal_2_, field="Elev_m", expression="!StrmHillElev_gridcode!", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Delete Field (Delete Field) (management)
        RootCarbonFinal_4_ = arcpy.management.DeleteField(in_table=RootCarbonFinal_3_, drop_field=["StrmHillElev_OBJECTID_1", "StrmHillElev_grid_code", "StrmHillElev_Shape_Leng", "RootCarbon_table_OBJECTID", "RootCarbon_table_grid_code", "RootCarbon_table_COUNT", "RootCarbon_table_AREA", "RootCarbon_table_SUM", "BGCarbon_table_OBJECTID", "BGCarbon_table_COUNT", "BGCarbon_table_AREA"])[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb", workspace=r"C:\Users\taller\Documents\ArcGIS\Projects\PythonModels\PythonModels.gdb"):
        Model23(*argv[1:])
